---
- hosts: all
  become: true
  tasks:
    - name: update apt
      apt: update_cache=yes

    - name: install depends
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - nginx-light
        - curl

    - name: network config
      notify: restart network
      copy:
        dest: /etc/network/interfaces
        content: |
          auto lo
          iface lo inet loopback

          auto eth0
          iface eth0 inet dhcp
                post-up ip route del default dev eth0 || true

          auto eth1
          iface eth1 inet static
                address 10.0.0.2
                netmask 255.255.255.0
                gateway 10.0.0.1
                
    - name: config nginx
      notify: nginx handler
      copy:
        dest: /etc/nginx/nginx.conf
        src: nginx-config

    - name: config dns
      copy:
        dest: /etc/resolv.conf
        src: resolv.conf
        
  handlers:
    - name: restart network
      service: name=networking state=restarted
    - name: nginx handler
      command: "systemctl restart nginx"
